language: python
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE "2fa_flask";' -U postgres
  - python manage.py db upgrade
script: coverage run manage.py test
env:
  - SECRET_KEY=not-so-secret DATABASE_URL=postgresql://postgres@localhost/2fa_flask export AUTHY_API_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
after_success:
  - coveralls
